### ISSUE TITLE
Collect challenges

### ISSUE THREAD

**Issue by Maab232001** [MIT-Emerging-Talent/ET6-foundations-group-28#16]
**Search for good challenges to share and discuss with the team**

**Comment by Maab232001** [comment]
_**Hello Guys I collected a list of good challenges you can start or think about in our project**_

    Greet Someone: Write a function greet(name) to print "Hello, [name]!".

    Add Two Numbers: Create a function add_numbers(a, b) that returns the sum of two numbers.

    Check Even or Odd: Write a function is_even(num) that checks if a number is even and returns True or False.

    Find the Maximum: Create a function find_max(a, b, c) to find the largest of three numbers.

    Calculate Factorial: Write a function factorial(n) to calculate the factorial of a number using recursion.

    Count Vowels: Create a function count_vowels(s) that counts the vowels in a given string.

    Reverse a String: Write a function reverse_string(s) that returns the reverse of a given string.

    Check Palindrome: Create a function is_palindrome(s) to check if a string is a palindrome.

    FizzBuzz: Write fizz_buzz(n) to print numbers 1–n, replacing multiples of 3 with "Fizz" and 5 with "Buzz".

    Convert Temperature: Write celsius_to_fahrenheit(c) to convert Celsius to Fahrenheit.

    Find Prime Numbers: Create is_prime(n) to determine if a number is prime or not.

    Multiplication Table: Write multiplication_table(n) to print the multiplication table of a number.

    String Length: Create string_length(s) to return the length of a given string.

    Sum of List: Write sum_list(lst) to calculate the sum of all elements in a list.

    Find Smallest in List: Create find_smallest(lst) to return the smallest number in a list.

**Comment by GhyathSAhmed** [comment]
great work Maab!!
i recommend adding each challenge as an issue and adding it to the TODO in the project so everyone can pick a challenge and start working

**Comment by AlhassenSabeeh** [comment]
It is very nice work with problems of all levels.
Thank you Maab!

**Comment by Maab232001** [comment]
Thanks Guys!

@GhyathSAhmed 
And yeah i think your recommendation is better, I will update it now

**Comment by ahdbasan** [comment]
Good job Maab!

**Comment by Shaymamohd** [comment]
Great work. This is a good mix of challenges
