### ISSUE TITLE
Reverse a String

### ISSUE THREAD

**Issue by Maab232001** [MIT-Emerging-Talent/ET6-foundations-group-28#27]
Reverse a String: Write a function reverse_string(s) that returns the reverse of a given string.

**Comment by ahdbasan** [comment]
![checks](https://github.com/user-attachments/assets/e1d274f3-2e1d-4c59-9f23-b1f3e87690a3)

**Comment by ahdbasan** [comment]
Q: Why the py_test (failed)?
![VSC 1](https://github.com/user-attachments/assets/ec62518e-7880-420e-b774-21a7278f0f16)

**Comment by GhyathSAhmed** [comment]
the py_test (failed) because it runs a command (python -m unittest) on the general repo which don't have a unit test folder so it would not find it that is why it does not pass because we save our solutions in the solutions folder.
and regarding the rest of the CI checks it because of other files that doesn't pass the checks because it checks the all the repo for the CI checks

**Comment by Adamx090** [comment]
@GhyathSAhmed I am confused still, maybe this would be something you can demo in the meeting.

**Comment by GhyathSAhmed** [comment]
@Adamx090 yes for sure Salih, I will demo this. I'm already working on it

**Comment by ahdbasan** [comment]
So it basically fails because it looks in the wrong place for tests, and the rest fail because there are issues in other files in the repo ? In Slack they talked about an init file, lets explore this further in the meeting.

**Comment by ahdbasan** [comment]
**I have an import error, Do I have to worry about it?**

**Comment by ahdbasan** [comment]
![Image](https://github.com/user-attachments/assets/dff229d1-8653-4829-939a-4f2e57a206f1)

**Comment by ahdbasan** [comment]
**Thats how it shows in terminal**   

![Image](https://github.com/user-attachments/assets/ea398620-5a69-459a-89fd-06890fca4410)

**Comment by AlhassenSabeeh** [comment]
Hi @ahdbasan,
Just change the line code 
from ..reverse_a_string import reverse_a_string

**Comment by ahdbasan** [comment]
I did it says the same, I think I'm just going to ignore it since it doesnt effect running the unittest

**Comment by ahdbasan** [comment]
Big thanks @AlhassenSabeeh for helping me fix my linting errors! I truly appreciate the time and effort you put into it!
